spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
server:
  port: ${SERVER_PORT}
  ssl:
    key-store: keystore.p12
    key-store-password: kschuquimarca
    key-store-type: PKCS12
    key-alias: tomcat
