apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-service-d
spec:
  selector:
    matchLabels:
      app: books-service-p
  replicas: 1
  template:
    metadata:
      labels:
        app: books-service-p
    spec:
      containers:
        - name: books-service-c
          image: books-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          env:
            - name: DB_URL
              value: jdbc:mysql://mysql-db-s:3306/books_db
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: SERVER_PORT
              value: "8090"

---

apiVersion: v1
kind: Service
metadata:
  name: books-service-s
spec:
  type: LoadBalancer
  selector:
    app: books-service-p
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
