apiVersion: v1
kind: Service
metadata:
  name: students-service-s
spec:
  type: LoadBalancer
  selector:
    app: students-service-p
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
