apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db-d
spec:
  selector:
    matchLabels:
      app: mysql-db-p
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-db-p
    spec:
      containers:
        - name: mysql-db-c
          image: mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-db-s
spec:
  selector:
    app: mysql-db-p
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
