apiVersion: apps/v1
kind: Deployment
metadata:
  name: students-service-d
spec:
  selector:
    matchLabels:
      app: students-service-p
  replicas: 2
  template:
    metadata:
      labels:
        app: students-service-p
    spec:
      containers:
        - name: students-service-c
          image: students-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              value: jdbc:mysql://mysql-db-s:3306/students_db
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: SERVER_PORT
              value: "8080"

---

apiVersion: v1
kind: Service
metadata:
  name: students-service-s
spec:
  type: LoadBalancer
  selector:
    app: students-service-p
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
